<a href="https://colab.research.google.com/github/Capta1nAlex/python/blob/main/03.09.24%20Reading%20matrix%20diagonally.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

def read_diagonal_elements(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    diagonal_elements = []
    for i in range(rows + cols - 1):
        diagonal = []
        for j in range(max(0, i - cols + 1), min(i + 1, rows)):
            diagonal.append(matrix[j][i - j])
        diagonal_elements.append(diagonal)

    return diagonal_elements



matrix = np.random.randint(1, 201, size=(4, 4)) # creating a matrix of random elements

print("Original Matrix:")
print(matrix)

diagonal_elements = read_diagonal_elements(matrix)
print("\nDiagonal Elements:")
for diagonal in diagonal_elements:
    print(diagonal)



Original Matrix:
[[123 138 188 195]
 [191  22 191 196]
 [175  39  59 185]
 [ 19  61 125  52]]

Diagonal Elements:
[123]
[138, 191]
[188, 22, 175]
[195, 191, 39, 19]
[196, 59, 61]
[185, 125]
[52]
